---
name: "workflow"

'on':
  push:
    branches:
      - feat/equipo_0
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: "Integration"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"

      - name: "Lint code"
        run: |
          echo "Linting repository"
      - name: "Run unit tests"
        run: |
          echo "Running unit tests"
                 name: Build and push
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Terraform init and Plan          
        uses: hashicorp/setup-terraform@v2
      - run: terraform init

      - id: plan
        run: terraform plan -no-color